### ISSUE TITLE
Charge the logo dynamically

### ISSUE THREAD

**Issue by clesaege** [kleros/uniswap-frontend#10]
Currently, the list of tokens takes a lot of time to load (compared to uniswap.exchange). My guess is that it first tries to get all token images before displaying anything.
We need to load images dynamically.

**Comment by eccentricexit** [comment]
The slow loading was due to fetching token information one by one instead of batches. 

Fixed in commit [585aa0](https://github.com/kleros/uniswap-frontend/commit/585aa03bb9f7e3144a00a84e00bc7a224cd106f1) and [d7fd4](https://github.com/kleros/uniswap-frontend/commit/d7fd45752bc42349bfb058eceb4299d71434b118) by deploying view contracts and fetching the information in batches.
